#!/bin/bash

if [ "$#" -eq 2 ]; then

    unset pyclass_username
    unset pyclass_password

    echo "Enter username:"
    read pyclass_username

    echo "Enter password"
    read -s pyclass_password

    curl -F "file=@$2" -F "enctype=multipart/form-data" "http://127.0.0.1:5000/user/$pyclass_username/password/$pyclass_password/upload/$1"
else

    printf "\nUsage:\n\t ./submit <problem_no> <file_name>\n\n"

fi

